### ISSUE TITLE
Error not found after install it

### ISSUE THREAD

**Issue by abdo-host** [candrianarijaona/slim-command#5]
Class 'Candrianarijaona\Command\Controller\GenerateControllerCommand' not found

```
use Candrianarijaona\Command\Controller\GenerateControllerCommand;

$app->add(
        new GenerateControllerCommand(__DIR__ . '/../app/Controllers')
);
```

**Comment by candrianarijaona** [comment]
Hello, 
Have you added the "candrianarijaona/slim-command" in your composer.json ?

**Comment by abdo-host** [comment]
yes i install it by  composer , and after install i use this code

use Candrianarijaona\Command\Controller\GenerateControllerCommand;

$baseDir  = __DIR__ . '/../app/Controllers';

$application->add(
    new GenerateControllerCommand($baseDir)
);

it say error
Class 'Candrianarijaona\Command\Controller\GenerateControllerCommand' not found

**Comment by candrianarijaona** [comment]
Sorry for delay, maybe you didn't include the autoload from the vendor. 

> require __DIR__ . '/vendor/autoload.php';
